# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trimal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trimal

  pod 'PinLayout'
  pod 'SwiftIcons', '~> 2.2.0'
  pod 'Cache'
  pod 'Alamofire', '~> 4.7'

end
